/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UdheheqesitRouteImport } from './routes/udheheqesit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UdheheqesitRoute = UdheheqesitRouteImport.update({
  id: '/udheheqesit',
  path: '/udheheqesit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lista': typeof ListaRoute
  '/settings': typeof SettingsRoute
  '/udheheqesit': typeof UdheheqesitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lista': typeof ListaRoute
  '/settings': typeof SettingsRoute
  '/udheheqesit': typeof UdheheqesitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lista': typeof ListaRoute
  '/settings': typeof SettingsRoute
  '/udheheqesit': typeof UdheheqesitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lista' | '/settings' | '/udheheqesit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lista' | '/settings' | '/udheheqesit'
  id: '__root__' | '/' | '/lista' | '/settings' | '/udheheqesit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListaRoute: typeof ListaRoute
  SettingsRoute: typeof SettingsRoute
  UdheheqesitRoute: typeof UdheheqesitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udheheqesit': {
      id: '/udheheqesit'
      path: '/udheheqesit'
      fullPath: '/udheheqesit'
      preLoaderRoute: typeof UdheheqesitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListaRoute: ListaRoute,
  SettingsRoute: SettingsRoute,
  UdheheqesitRoute: UdheheqesitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
